/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Auth: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.exp <- map["exp"]
    self.message <- map["message"]
    self.status.value <- map["status"]
    self.token <- map["token"]
  }
}
