/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension Posts: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.status.value <- map["status"]

    // MARK: Relationships
    self.posts <- (map["posts"], ListTransform<Post>())
  }
}
