/* DO NOT EDIT | Generated by gyro */

import ObjectMapper

extension User: Mappable {

  // MARK: Initializers
  convenience init?(map: Map) {
    self.init()
  }

  // MARK: Mappable
  func mapping(map: Map) {
    // MARK: Attributes
    self.id.value <- map["id"]
    self.created_at <- map["created_at"]
    self.dni <- map["dni"]
    self.email <- map["email"]
    self.lastname <- map["lastname"]
    self.name <- map["name"]
    self.password_digest <- map["password_digest"]
    self.updated_at <- map["updated_at"]
  }
}
