/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Auth: Object, Decodable {

  enum Attributes: String {
    case exp = "exp"
    case message = "message"
    case status = "status"
    case token = "token"
  }

  @objc dynamic var exp: String?
  @objc dynamic var message: String?
  let status = RealmOptional<Bool>()
  @objc dynamic var token: String?

}
