/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class User: Object, Decodable {

  private enum Attributes: String, CodingKey {
    case id = "id" /* Primary Key */
    case created_at = "created_at"
    case dni = "dni"
    case email = "email"
    case lastname = "lastname"
    case name = "name"
    case password_digest = "password_digest"
    case updated_at = "updated_at"
  }

  @objc dynamic var id: Int64 = 0 /* Primary Key */
  @objc dynamic var created_at: String?
  @objc dynamic var dni: String?
  @objc dynamic var email: String?
  @objc dynamic var lastname: String?
  @objc dynamic var name: String?
  @objc dynamic var password_digest: String?
  @objc dynamic var updated_at: String?

  override static func primaryKey() -> String? {
    return "id"
  }

}
