/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Users: Object, Decodable {

  private enum Attributes: String, CodingKey {
    case status = "status"
  }

  enum Relationships: String {
    case users = "users"
  }

  let status = RealmOptional<Bool>()
  var users = List<User>()

}
