on:
  push:
    branches:
      - master
      - develop
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          pod install
          xcodebuild clean build -workspace Newspaper.xcworkspace -scheme Newspaper -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
